### ISSUE TITLE
Merge conflict on Robot.cpp

### ISSUE THREAD

**Issue by Ayilay** [frc-team-3341/Team-3341-Recycle-Rush#8]
Is anyone going to fix this? I can fix it if no one will

**Comment by Ayilay** [comment]
@prathyushk @TheTrueMaster

**Comment by tpankaj** [comment]
I'll take a look.

From,
Tushar Pankaj

**Comment by tpankaj** [comment]
Should be easy to fix. I'll do it when I get on the computer.

**Comment by tpankaj** [comment]
Well I didn't finish this because of being in the hospital but I'll do it now.
